export const STRINGS = {
  OPTIONS_SCREEN_HINT: 'Enter the options you’re choosing between.',
  GENERATE_QUESTIONS_BUTTON_TITLE: 'HELP ME DECIDE',
  TRY_AGAIN_BUTTON_TITLE: 'LET’S TRY AGAIN',
  HISTORY_SCREEN_TITLE: 'Your past decisions',
  HISTORY_EMPTY: 'Decisions you make will appear here.',
  HISTORY_RECOMMENDATION_TITLE: 'Recommendation',
  HISTORY_ANSWERS_TITLE: 'Your answers',
  BACK_BUTTON_TITLE: 'BACK',
  DELETE_BUTTON_TITLE: 'DELETE',
  DELETE_ENTRY_ALERT_TITLE: 'Delete this decision?',
  DELETE_ENTRY_ALERT_MESSAGE: 'It will be removed from your history.',
  DELETE_ENTRY_ALERT_CONFIRM: 'Delete',
  ALERT_CANCEL_BUTTON_TITLE: 'Cancel',
  SETTINGS_SCREEN_TITLE: 'Settings',
  SAVED_DECISIONS_LABEL: 'Saved decisions: ',
  CLEAR_HISTORY_BUTTON_TITLE: 'CLEAR ALL HISTORY',
  CLEAR_HISTORY_ALERT_TITLE: 'Clear all history?',
  CLEAR_HISTORY_ALERT_MESSAGE:
    'All saved decisions will be deleted. This can’t be undone.',
  CLEAR_HISTORY_ALERT_CONFIRM: 'Clear',
  NEW_DECISION_TAB_TITLE: 'New decision',
  HISTORY_TAB_TITLE: 'History',
  SETTINGS_TAB_TITLE: 'Settings',
  SERVICE_ERROR_ALERT_TITLE: 'Service Temporarily Unavailable',
  SERVICE_ERROR_ALERT_MESSAGE: 'Please try again later',
};
