# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Android Production Build and Deploy to Play Store Production"
  lane :deploy_new_version do
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      properties: {
        "android.injected.signing.store.file" => File.expand_path(ENV['KEYSTORE_FILE'], __dir__),
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
    }
  )

  upload_to_play_store(
    track: 'internal',
    release_status: 'completed',
    skip_upload_apk: true,
    aab: File.absolute_path('../app/build/outputs/bundle/release/app-release.aab'),
  )

  firebase_app_distribution(
    app: ENV['FIREBASE_ANDROID_APP_ID'],
    firebase_cli_token: ENV['FIREBASE_TOKEN'],
    groups: 'testers',
    android_artifact_type: "AAB",
    service_credentials_file: "play-account.json",
    android_artifact_path: File.absolute_path('../app/build/outputs/bundle/release/app-release.aab'),
    release_notes: "Lots of amazing new features to test out!",
  )
  end
end
